### ISSUE TITLE
[Xcode 16.1] iOS 14.6 crashing with Realm 10.45.1

### ISSUE THREAD

**Issue by shijian123** [realm/realm-swift#8708]
### How frequently does the bug occur?

Always

### Description

<img width="1496" alt="截屏2024-11-01 16 01 30" src="https://github.com/user-attachments/assets/452badfd-d92c-412c-ba55-f407d2f26820">

Try adding the -Wl,-ld_classic options to the OTHER_LDFLAGS build in the project settings. Still doesn't work

### Can you reproduce the bug?

Always

### Version

10.45.1

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Xcode16.1 IOS14.6

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by tentenlee100** [comment]
same issue on ios 14.8.1, but ios 15.7 is fine

**Comment by GordonLJY** [comment]
So do I. works well on iOS 15 or later but crashes when running on iOS 14.x.

**Comment by hrjun** [comment]
Same issue on Xcode 16.1 + Realm 10.54.1 + iOS 14.8.1, but works fine with Xcode 16.0.

**Comment by lkuraer** [comment]
Same issue on Xcode 16.1 + Realm 10.53.0 + iOS 14x, but works fine with other ios versions

**Comment by kingnight** [comment]
Same issue on Xcode 16.1 + Realm 10.54.1 + iOS 14.4,  please fix

**Comment by kingnight** [comment]
> The issue is caused by Xcode 16.1 trying to link in the Swift Concurrency back deployment library in iOS < 15. It does this by incorrectly linking to /usr/lib/swift_Concurrency.lib while it should link to @rpath/swift_Concurrency.lib.
> 
> I haven't seen this in other SPM packages, so it's likely a combination of this SPM package's configuration + a bug in Xcode 16.1

any workaround can take ?

**Comment by ZhangPan0825** [comment]
The same issue exists on Xcode 16.1+Realm 10.52.3+iOS 14x

**Comment by Jride** [comment]
This is currently blocking us from releasing our app that is needing to support iOS 14

**Comment by dsdsk** [comment]
I set the “minimum developments” to 13 or more and it stopped crashing.

**Comment by Touchgram** [comment]
It was reported for iOS13 in the duplicate [8723](https://github.com/realm/realm-swift/issues/8723)

> I set the “minimum developments” to 13 or more and it stopped crashing.

that didn't fix things for me. I get the same crash in `RLMSetMainActor(MainActor.shared)`

**Comment by akinoavx13** [comment]
You can archive using Xcode Cloud with Xcode 15, it works.

**Comment by Touchgram** [comment]
I am building now with the released Xcode 16.2
Crash reproduced on iOS 14.7.1 with Realm versions;

- 10.49.2
- 10.48.2 (has privacy manifest)

Reverting to Xcode 16.0 and testing with Realm 10.48.2 **does not crash** - it was some change in Xcode 16.1 causing the problem.

Note [Apple submission rules](https://developer.apple.com/ios/submit/) say, currently

> must be built with a minimum of Xcode 15 and the iOS 17 SDK. Starting April 2025, ... must be built with the iOS 18 SDK

So we have a second workaround if necessary, although that means missing out on the new icon handling of Xcode 16

**Comment by Touchgram** [comment]
Version [10.38.3](https://github.com/realm/realm-swift/blob/master/CHANGELOG.md#10383-release-notes-2023-04-28) is the highest release that builds and runs with Xcode 16.2 on iOS14.

v10.39.1 introduced a compilation failure on older OS that wasn't fixed until 10.40.1.

**The problem causing Xcode 16.1/2 to cause crashes was introduced somewhere between 10.38.3 and 10.40.1)**

I am unable to test my iOS 12 and 13 devices with that Xcode due "could not locate device support files".

**Comment by akinoavx13** [comment]
Has the reported bug been fixed in version 10.54.2 released last week?

**Comment by akinoavx13** [comment]
Confirmed: The bug persists in version 20.0.1. 🫠

**Comment by vasyl-nadtochii** [comment]
+1 
Issue persists for iOS < 15 in xcode 16.2 with latest Realm version

**Comment by aehlke** [comment]
Realm is dead. If you need this fixed for iOS < 15, someone here needs to contribute a PR. MongoDB isn't listening anymore.

**Comment by z3DD3r** [comment]
If u don’t need to support iOS 12.x then solution described here:
https://github.com/realm/realm-swift/issues/8738#issuecomment-2629095061

Works fine on iOS 13.x and iOS 14.x when building with Xcode 16.2

**Comment by snail-Lin** [comment]
Xcode 16.3 should be fine now. I’ve already tested it on an iOS 12 device, and there are no crashes.

**Comment by snail-Lin** [comment]
There are no issues on iOS 14.2 either.

**Comment by ChengJingH** [comment]
I updated Xcode to Xcode16.3 and ran iOS 14.7 and this problem did not occur.
